# This workflow is triggered when pushing to the main branch, 
# it builds the react app in benchmark and publishes it just using npm run deploy
name: Build and Deploy App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies and deploy
      run: |
        cd ./benchmark/benchmark-app/
        pwd
        ls
        npm install
        npm run deploy
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'